version: "3.9"

services:
  server:
    build: ./tech-int3-server
    ports:
      - "3001:3001"
    volumes:
      - ./tech-int3-server:/app
      - /app/node_modules

  client:
    build: ./tech-int3-client
    ports:
      - "5173:5173"
    volumes:
      - ./tech-int3-client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_PROXY_TARGET=http://server:3001
